[workspace]
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
name = "eOn"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
# Pins from environment.yml
# TODO(rg): Maybe take another look
eigen = ">=3.4,<3.5"
fmt = "<=10"
spdlog = "<=1.14"
# Pin python for torch
python = ">=3.11.5,<3.13"
# End manual pins
cmake = ">=4.0.3,<5"
highfive = ">=2.10.1,<3"
meson = ">=1.8.2,<2"
ninja = ">=1.12.1,<2"
gfortran = ">=14.2.0,<15.2"
pkgconf = ">=2.4.3,<3"
openblas = ">=0.3.29,<0.4"
pip = ">=25.1.1,<26"
pipx = ">=1.7.1,<2"
numpy = ">=2.3.0,<3"

[environments]
metatomic = {features = ["metatomic"]}
dev = {features = ["lint"]}

[feature.metatomic]
# vesin torch has a wheel issue with macos x86_64
platforms = ["linux-64", "osx-arm64"]

[feature.metatomic.pypi-dependencies]
torch = ">=2.7.1, <3"
metatomic-torch = ">=0.1.2, <0.2"
metatensor-torch = ">=0.7.6, <0.8"
metatensor = ">=0.2.0, <0.3"
vesin-torch = ">=0.3.7, <0.4"
vesin = ">=0.3.7, <0.4"

[feature.ams.dependencies]
boost-cpp = "*"
abseil-cpp = "*"

[feature.lint.dependencies]
cppcheck = "*"
cpplint = "*"
clang-format = "*"
ruff = "*"
pre-commit = "*"
