/*
** This file is part of eOn.
**
** SPDX-License-Identifier: BSD-3-Clause
**
** Copyright (c) 2010--present, eOn Development Team
** All rights reserved.
**
** Repo:
** https://github.com/TheochemUI/eOn
*/

/// Approval test for SoapDescriptorEngine against Python (featomic) reference.
///
/// Reference data generated by gen_soap_reference.py in
/// client/gtests/data/systems/hcn/.  Hyperparameters must match exactly.

#include "SoapDescriptorEngine.h"
#include "catch2/catch_amalgamated.hpp"

#include <cmath>
#include <vector>

using namespace Catch::Matchers;

// ---------- Reference values from gen_soap_reference.py ----------
// HCN system: C at ~(12.499, 12.500, 12.542)
//              N at ~(12.501, 12.500, 11.384)
//              H at ~(12.501, 12.500, 13.616)
// 25 Ang cubic cell, PBC=[true, true, true]
// SOAP: cutoff=6.0, smoothing=0.5, density=0.3, l_max=4, n_max=6

static constexpr int REF_N_ATOMS = 3;
static constexpr int REF_DESC_DIM = 4410;
static constexpr double REF_DESC_NORM = 5.400780931248864e-01;
static constexpr double REF_JAC_FROB_NORM = 8.510369153885023e-01;

// First 5 non-zero descriptor values (indices 0..4 are actually non-zero)
static constexpr double REF_DESC_VALS[] = {
    2.206938811800235e-01,  // [0]
    -9.050074058317269e-02, // [1]
    1.888946574122227e-02,  // [2]
    -2.874437334925352e-02, // [3]
    2.409612084431522e-02,  // [4]
};


namespace tests {

class FeatomicTest {
public:
  FeatomicTest() {}

  void SetUp() {
    // HCN positions (from pos.con / gen_soap_reference.py)
    positions_ = torch::tensor(
        {{12.49920530576333633, 12.49960080579726807, 12.54209698318736699},
         {12.50069048683807615, 12.50039919420273193, 11.38365673946223389},
         {12.50079469423666367, 12.50006476947390155, 13.61634326053776611}},
        torch::dtype(torch::kFloat64));

    types_ = torch::tensor({6, 7, 1}, torch::kInt32);

    cell_ =
        torch::tensor({{25.0, 0.0, 0.0}, {0.0, 25.0, 0.0}, {0.0, 0.0, 25.0}},
                       torch::dtype(torch::kFloat64));

    pbc_ = torch::tensor({true, true, true}, torch::kBool);

    engine_ = std::make_unique<SoapDescriptorEngine>(
        /*cutoff=*/6.0,
        /*smoothing_width=*/0.5,
        /*density_width=*/0.3,
        /*max_angular=*/4,
        /*max_radial=*/6);
  }

  void TearDown() { engine_.reset(); }

protected:
  torch::Tensor positions_;
  torch::Tensor types_;
  torch::Tensor cell_;
  torch::Tensor pbc_;
  std::unique_ptr<SoapDescriptorEngine> engine_;
};

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: descriptor dimension matches Python",
                 "[FeatomicTest]") {
  SetUp();

  auto descriptor = engine_->compute(positions_, types_, cell_, pbc_);

  REQUIRE(descriptor.dim() == 1);
  REQUIRE(descriptor.size(0) == REF_DESC_DIM);
  REQUIRE(engine_->descriptorDim() == REF_DESC_DIM);

  TearDown();
}

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: descriptor norm matches Python",
                 "[FeatomicTest]") {
  SetUp();

  auto descriptor = engine_->compute(positions_, types_, cell_, pbc_);

  double norm = descriptor.norm().item<double>();
  // Allow 1e-6 relative tolerance for numerical differences between
  // Python/C++ featomic implementations
  REQUIRE_THAT(norm, WithinRel(REF_DESC_NORM, 1e-6));

  TearDown();
}

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: descriptor values spot-check",
                 "[FeatomicTest]") {
  SetUp();

  auto descriptor = engine_->compute(positions_, types_, cell_, pbc_);
  auto acc = descriptor.accessor<double, 1>();

  // Check first 5 descriptor components against Python reference
  for (int i = 0; i < 5; i++) {
    INFO("descriptor[" << i << "]");
    REQUIRE_THAT(acc[i], WithinRel(REF_DESC_VALS[i], 1e-6));
  }

  TearDown();
}

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: descriptor has no NaN or Inf",
                 "[FeatomicTest]") {
  SetUp();

  auto descriptor = engine_->compute(positions_, types_, cell_, pbc_);
  auto acc = descriptor.accessor<double, 1>();

  for (int64_t i = 0; i < descriptor.size(0); i++) {
    INFO("descriptor[" << i << "]");
    REQUIRE(std::isfinite(acc[i]));
  }

  TearDown();
}

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: Jacobian Frobenius norm matches Python",
                 "[FeatomicTest]") {
  SetUp();

  auto jacobian =
      engine_->computeJacobian(positions_, types_, cell_, pbc_);

  REQUIRE(jacobian.dim() == 2);
  REQUIRE(jacobian.size(0) == REF_DESC_DIM);
  REQUIRE(jacobian.size(1) == 3 * REF_N_ATOMS);

  double frob_norm = jacobian.norm().item<double>();
  REQUIRE_THAT(frob_norm, WithinRel(REF_JAC_FROB_NORM, 1e-6));

  TearDown();
}

TEST_CASE_METHOD(FeatomicTest,
                 "SoapDescriptorEngine: Jacobian has no NaN or Inf",
                 "[FeatomicTest]") {
  SetUp();

  auto jacobian =
      engine_->computeJacobian(positions_, types_, cell_, pbc_);

  // Check all entries are finite
  bool all_finite =
      torch::all(torch::isfinite(jacobian)).item<bool>();
  REQUIRE(all_finite);

  TearDown();
}

TEST_CASE_METHOD(
    FeatomicTest,
    "SoapDescriptorEngine: Jacobian non-zero row spot-check (row 245)",
    "[FeatomicTest]") {
  SetUp();

  auto jacobian =
      engine_->computeJacobian(positions_, types_, cell_, pbc_);

  // Row 245 is the first non-zero Jacobian row for HCN with these hypers
  // Reference values from gen_soap_reference.py
  constexpr double ref_row245[] = {
      2.800585420302581e-04,  8.175282066878933e-05,  1.892877992164866e-01,
      0.0,                    0.0,                     0.0,
      -2.800585420302581e-04, -8.175282066878933e-05, -1.892877992164866e-01,
  };

  auto row = jacobian[245];
  auto acc = row.accessor<double, 1>();

  for (int c = 0; c < 9; c++) {
    INFO("jacobian[245," << c << "]");
    if (std::abs(ref_row245[c]) > 1e-15) {
      // Non-zero: relative tolerance
      REQUIRE_THAT(acc[c], WithinRel(ref_row245[c], 1e-6));
    } else {
      // Zero: absolute tolerance
      REQUIRE_THAT(acc[c], WithinAbs(0.0, 1e-12));
    }
  }

  TearDown();
}

TEST_CASE_METHOD(
    FeatomicTest,
    "SoapDescriptorEngine: Jacobian has non-trivial content",
    "[FeatomicTest]") {
  SetUp();

  // First verify the autograd graph is connected
  auto descriptor = engine_->compute(positions_, types_, cell_, pbc_);
  INFO("descriptor.requires_grad() = " << descriptor.requires_grad());
  INFO("descriptor.grad_fn() defined = "
       << (descriptor.grad_fn() != nullptr));
  REQUIRE(descriptor.requires_grad());

  // Now compute the full Jacobian
  auto jacobian =
      engine_->computeJacobian(positions_, types_, cell_, pbc_);

  // The Jacobian must not be all zeros — that would mean autograd
  // failed to connect positions to the descriptor graph.
  double frob_norm = jacobian.norm().item<double>();
  INFO("Jacobian Frobenius norm = " << frob_norm);
  REQUIRE(frob_norm > 0.1);

  // Count non-zero rows (L2 norm along dim=1, i.e. per row)
  auto row_norms = torch::norm(jacobian, 2, /*dim=*/1);
  auto nz_count = torch::sum(row_norms > 1e-15).item<int64_t>();

  INFO("Non-zero Jacobian rows: " << nz_count << " / " << jacobian.size(0));

  // Print first few non-zero row indices for debugging
  auto nz_mask = row_norms > 1e-15;
  auto nz_indices = torch::where(nz_mask)[0];
  if (nz_indices.size(0) > 0) {
    INFO("First non-zero row index: " << nz_indices[0].item<int64_t>());
  }

  // Python reference has 2499 non-zero rows out of 4410
  REQUIRE(nz_count > 2000);

  TearDown();
}

} /* namespace tests */
