"""Consume Cap'n Proto L0 field graph (schema/eon_params.capnp).

The catalog is generated by ``tools/params_ssot/codegen.py``. Covered groups
must not gain peer field authors in config.yaml / schema.py without updating
the Cap'n Proto schema and regenerating.
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Tuple

from eon._params_ssot_catalog import CATALOG

COVERED_SECTIONS = frozenset(CATALOG["sections"].keys())


def catalog() -> dict:
    return CATALOG


def section_fields(section: str) -> List[dict]:
    return list(CATALOG["sections"].get(section, {}).get("fields", []))


def scalar_fields(section: str) -> List[dict]:
    return [f for f in section_fields(section) if not f.get("nested")]


def defaults_for(section: str) -> Dict[str, Any]:
    return {
        f["snake"]: f["default"]
        for f in scalar_fields(section)
        if f.get("default") is not None
    }


def all_field_ids() -> List[str]:
    out = []
    for sec, data in CATALOG["sections"].items():
        for f in data["fields"]:
            if f.get("nested"):
                continue
            out.append(f"{sec}.{f['snake']}")
    return out


def has_field(section: str, key: str) -> bool:
    return f"{section}.{key}" in set(all_field_ids())
