name: "Build EON with GPRD"
# TODO: Include master once merged
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  build_eon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get private submodules
      env:
        SSHK: ${{ secrets.SUBMODULE_PRIVATE }}
      run: |
        rm -rf client/subprojects/gprdimer && mkdir -p $HOME/.ssh
        printf "%s\n" "$SSHK" > $HOME/.ssh/ssh.key
        chmod 600 $HOME/.ssh/ssh.key
        export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
        git clone git@github.com:TheochemUI/gpr_optim subprojects/gpr_optim
    - name: Fix GPRD branch
      run: |
        cd subprojects/gpr_optim
        git checkout e25fd6736f6a521ca114f991ca488d57273025e4
    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        activate-environment: true
        environments: >-
          dev
    - name: Install eon
      shell: pixi run bash -e {0}
      run: |
        meson setup --reconfigure bbdir  \
        --prefix=$CONDA_PREFIX           \
        --buildtype release              \
        --libdir=lib
        meson install -C bbdir
    - name: Integration Tests
      shell: pixi run bash -e {0}
      run: |
        cd client/gtests/data/saddle_search/
        eonclient
