name: Build and Deploy Documentation

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true
          environments: >-
            docs

      - name: Generate Docs
        shell: pixi run bash -e {0}
        run: |
          pixi r makedocs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
