name: Build and Deploy Documentation

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true
          environments: >-
            docs

      - name: Generate Docs
        shell: pixi run bash -e {0}
        run: |
          pixi r makedocs

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: html

  deploy:
    name: Deploy to gh-pages
    needs: build_docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'TheochemUI/eOn' && !contains(github.event.head_commit.message, 'ImgBot')
    permissions:
      contents: write
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: ./html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./html
          enable_jekyll: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
