name: pre-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
      cache: true
      cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      activate-environment: true
      environments: >-
        dev
    - name: Run precommit
      shell: pixi run bash -e {0}
      run: |
        uvx pre-commit run -a -vvv
